name: test_flutter_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  http: ^1.2.1
  syncfusion_flutter_charts: ^24.2.7
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size