name: hackaton_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  foundation: ^0.0.5
  http: ^1.2.1
  mailer: ^6.1.0
  path: ^1.9.0
  sprintf: ^7.0.0
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^0.4.3
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/properties/

